homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_lat
  longitude: !secret location_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 24
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
# Enables the frontend
frontend:

# Enables configuration UI
config:

ios:


mqtt:
  broker: 192.168.1.170

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  api_password: !secret http_api_pwd
  #ssl_certificate: !secret ssl_cert
  #ssl_key: !secret ssl_key
  #base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: True
  trusted_proxies:
    - 127.0.0.1
    - 192.168.1.170
    - ::1
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - fd00::/8
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Verizure larm
verisure:
  username: !secret verisure_username
  password: !secret verisure_pwd
  door_window: 1

# Energy consumption
sensor:
  - platform: eliqonline
    access_token: !secret eliqonline_token
    channel_id: 6870

# ESP8266 (wemos d1 mini,lolin) switch using MQTT
light:
  - platform: mqtt
    name: "Trappbelysning"
    state_topic: "home/staircase/upper/handlelight/state"
    command_topic: "home/staircase/upper/handlelight/set"
    payload_on: "100"
    payload_off: "0"
    brightness_scale: 100
    brightness_state_topic: 'home/staircase/upper/handlelight'
    brightness_command_topic: 'home/staircase/upper/handlelight/set'
    on_command_type: 'brightness'
    retain: true
  - platform: mqtt
    name: "Nischbelysning"
    state_topic: "home/staircase/upper/boxlight/state"
    command_topic: "home/staircase/upper/boxlight/set"
    payload_on: "100"
    payload_off: "0"
    brightness_scale: 100
    brightness_state_topic: 'home/staircase/upper/boxlight'
    brightness_command_topic: 'home/staircase/upper/boxlight/set'
    on_command_type: 'brightness'
    retain: true